### ISSUE TITLE
[minor] Nav - extra space after BAD

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-teach-advocate-overview#1]
<img width="203" alt="bad-nav-space" src="https://user-images.githubusercontent.com/6991814/44304897-a6153c00-a32f-11e8-9f2a-f1b270015fc2.png">

And, do we want the "off WAI site nav" icon?

**Comment by yatil** [comment]
Can you please try to force reload the page to reload your CSS & icons? We changed around the icons, and it seems like an old version of the icons is cached on your end. (The non-available icon taking up space underneath the BAD menu item, being invisible.)

Works fine here:

<img width="328" alt="screen shot working here" src="https://user-images.githubusercontent.com/58862/44307469-5a03df00-a3a3-11e8-80c1-eb8466cb2f0f.png">
