### ISSUE TITLE
[es update needed]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-teach-advocate-overview#17]
Hi @cmuncharaz

We will be promoting translations the week of 17 May, along with Global Accessibility Awareness Day (GAAD).

Would you be able to update this translation? Or, should we ask someone else to update it?

https://raw.githubusercontent.com/w3c/wai-teach-advocate-overview/master/content/index.es.md

I added the new text in English:
* Curricula on Web Accessibility: A Framework to Build Your Own Courses ...

Remember to also update ``` last_updated: 2019-07-17 ``` with the date of the translation

**Comment by cmuncharaz** [comment]
Pull request: https://github.com/w3c/wai-teach-advocate-overview/pull/18
